# Generated by Django 6.0.7 on 2026-07-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(editable=False, unique=True, verbose_name='item number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('soup', 'Soup'), ('main_course', 'Main course'), ('dessert', 'Dessert'), ('salad', 'Salad'), ('side', 'Side dish'), ('beverage', 'Beverage')], max_length=20, verbose_name='dish type')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='is vegan')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='nomnom.menu', verbose_name='Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Day price for this dish on this menu', max_digits=8, verbose_name='Price')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_dishes', to='nomnom.dish', verbose_name='Dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dishes', to='nomnom.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Menu dish',
                'verbose_name_plural': 'Menu dishes',
                'ordering': ['menu', 'dish'],
                'constraints': [models.UniqueConstraint(fields=('menu', 'dish'), name='unique_menu_dish')],
            },
        ),
    ]
